In [35]:
import pandas as pd
import numpy as np

In [36]:
df_raw = pd.read_excel("student_performance_batchwise_2018_2025.xlsx")
df = df_raw.copy()
df = df.sort_values(['Student_ID', 'Semester'])

In [37]:
df.head()

,Student_ID,Student_Name,Batch,Semester,Year,Mid1,Mid2,Internals,EndTerm,Attendance,Total_Marks,SGPA,Performance_Type,Placement
0,S0001,Neha Pal,2018,1,2018,9.82,5.10,11.46,73.87,78.8,63.32,6.09,Low_Performer,Not Placed
1,S0001,Neha Pal,2018,2,2018,7.48,7.55,9.98,54.82,91.4,52.42,6.31,Low_Performer,Not Placed
2,S0001,Neha Pal,2018,3,2019,9.16,10.36,8.06,42.76,87.8,48.97,6.59,Low_Performer,Not Placed
3,S0001,Neha Pal,2018,4,2019,6.56,10.50,15.56,48.40,87.2,56.82,6.05,Low_Performer,Not Placed
4,S0001,Neha Pal,2018,5,2020,11.19,4.43,9.45,48.62,83.7,49.38,5.39,Low_Performer,Not Placed

In [38]:
# Recreate rolling dip flag
df_roll = df.copy()
df_roll['Rolling_Avg'] = df_roll.groupby('Student_ID')['SGPA'].transform(
    lambda x: x.expanding().mean()
)
df_roll['Rolling_STD'] = df_roll.groupby('Student_ID')['SGPA'].transform(
    lambda x: x.expanding().std()
).fillna(0)

In [39]:
df_roll['Is_Dip_Roll'] = df_roll['SGPA'] < (df_roll['Rolling_Avg'] - df_roll['Rolling_STD'])

In [40]:
print(df_roll.shape)

(2752, 17)

In [41]:
df_roll.head()

,Student_ID,Student_Name,Batch,Semester,Year,Mid1,Mid2,Internals,EndTerm,Attendance,Total_Marks,SGPA,Performance_Type,Placement,Rolling_Avg,Rolling_STD,Is_Dip_Roll
0,S0001,Neha Pal,2018,1,2018,9.82,5.10,11.46,73.87,78.8,63.32,6.09,Low_Performer,Not Placed,6.090,0.000000,False
1,S0001,Neha Pal,2018,2,2018,7.48,7.55,9.98,54.82,91.4,52.42,6.31,Low_Performer,Not Placed,6.200,0.155563,False
2,S0001,Neha Pal,2018,3,2019,9.16,10.36,8.06,42.76,87.8,48.97,6.59,Low_Performer,Not Placed,6.330,0.250599,False
3,S0001,Neha Pal,2018,4,2019,6.56,10.50,15.56,48.40,87.2,56.82,6.05,Low_Performer,Not Placed,6.260,0.247925,False
4,S0001,Neha Pal,2018,5,2020,11.19,4.43,9.45,48.62,83.7,49.38,5.39,Low_Performer,Not Placed,6.086,0.444387,True

Collasping all Sems rows in single Row

In [42]:
def build_student_features(student_df):
    student_df = student_df.sort_values("Semester").copy()
    sgpa = student_df["SGPA"].values
    sems = student_df["Semester"].values

    
    expanding_mean = student_df['SGPA'].expanding().mean()
    expanding_std = student_df['SGPA'].expanding().std().fillna(0)
    is_dip = student_df['SGPA'] < (expanding_mean - expanding_std)

    
    # Slop for Trend
    if len(sgpa)>1:
        polyfit = np.polyfit(sems, sgpa, 1)
        slope = polyfit[0]
    else:
        slope = 0.0


    return pd.Series({
        'current_sgpa' : sgpa[-1],
        'sgpa_mean' : sgpa.mean(),
        "sgpa_trend" : round(slope, 4),
        'consistency_score' : sgpa.std(),
        'dip_count': int(is_dip.sum()),           # Total dip count
        'last_sem_dip': int(is_dip.iloc[-1]),      # Current dip status
        'attendance_mean': student_df['Attendance'].mean(),
        'internals_avg':     student_df['Internals'].mean()
        
    })
        
# Apply → 224 rows (one per student)
df_features = df_roll.groupby('Student_ID').apply(build_student_features).reset_index()

C:\Users\ani77\AppData\Local\Temp\ipykernel_8160\2021020316.py:33: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_features = df_roll.groupby('Student_ID').apply(build_student_features).reset_index()

In [43]:
print(df_features.shape)  # (224, 11)

(344, 9)

In [44]:
df_features.head()

,Student_ID,current_sgpa,sgpa_mean,sgpa_trend,consistency_score,dip_count,last_sem_dip,attendance_mean,internals_avg
0,S0001,5.03,5.89500,-0.1560,0.480833,3.0,1.0,83.4750,9.77250
1,S0002,7.15,7.59500,-0.0452,0.492874,0.0,0.0,72.7750,12.14000
2,S0003,7.90,7.07000,0.1838,0.482986,0.0,0.0,77.2500,11.51250
3,S0004,5.11,5.33875,-0.1763,0.571849,3.0,0.0,81.0125,9.85625
4,S0005,5.39,6.02625,-0.2235,0.553284,4.0,1.0,82.8375,10.76875

In [45]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [46]:
def build_training_features(student_df):
    features = build_student_features(student_df)
    # Add target label
    features["placement_ready"] = (
        student_df["Placement"].iloc[0]
    )
    return pd.Series(features)

df_features = (
    df_roll
    .groupby("Student_ID")
    .apply(build_training_features)
    .reset_index()
)


FEATURES = [
    "current_sgpa", "sgpa_mean", "sgpa_trend", "consistency_score", "dip_count", 'last_sem_dip',
    'attendance_mean', 'internals_avg'
]

X = df_features[FEATURES]

y = df_features["placement_ready"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

C:\Users\ani77\AppData\Local\Temp\ipykernel_8160\4110273485.py:12: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(build_training_features)

RandomForestClassifier(random_state=42)

In [47]:
print(classification_report(y_test, rf_model.predict(X_test),
      target_names=['Not Ready', 'Placement Ready']))

                 precision    recall  f1-score   support

      Not Ready       0.74      0.82      0.78        34
Placement Ready       0.81      0.71      0.76        35

       accuracy                           0.77        69
      macro avg       0.77      0.77      0.77        69
   weighted avg       0.77      0.77      0.77        69

In [48]:
from sklearn.metrics import accuracy_score
y_pred = rf_model.predict(X_test)
acc_RandomFor = accuracy_score(y_test, y_pred)
print(acc_RandomFor)

0.7681159420289855

In [49]:
importance = pd.Series(
    rf_model.feature_importances_,
    index=FEATURES
).sort_values(ascending=False)

print(importance)

internals_avg        0.223005
current_sgpa         0.179413
sgpa_mean            0.168227
sgpa_trend           0.147328
consistency_score    0.129051
attendance_mean      0.097888
dip_count            0.043574
last_sem_dip         0.011513
dtype: float64

### Predicting a students v

### Only FOR Random Forest

In [50]:
def predict_student_readiness(student_df, rf_model, feature_list):
    # 1. Generate features automatically
    engineered_features = build_student_features(student_df)
    
    # 2. Convert to DataFrame and ensure correct column order
    input_df = pd.DataFrame([engineered_features])[feature_list]
    
    # 3. Get prediction and probability
    prediction = rf_model.predict(input_df)[0]
    probability = rf_model.predict_proba(input_df)[0][1]
    
    return {
        "is_ready": prediction,
        "readiness_score": round(probability * 100, 2),
        "total_dips_detected": engineered_features['dip_count'],
        "current_sem_is_dip": bool(engineered_features['last_sem_dip'])
    }

In [51]:
# Raw data: No 'Is_Dip_Roll' or 'Placement' columns needed
new_student = pd.DataFrame({
    "Semester": [1, 2, 3,4,5,6,7],
    "SGPA": [7.45, 8.12, 6.50, 7.12, 7.45, 7.6, 7.68], # Dropped from 8.12 to 6.50 (A Dip)
    "Attendance": [82, 85, 80, 70,72,22,15],
    "Internals": [21, 24, 23, 21, 24, 23, 20]
})

# Run prediction
result = predict_student_readiness(new_student, rf_model, FEATURES)
print(f"Readiness: {result['is_ready']}")
print(f"Probability: {result['readiness_score']}%")
print(f"Dips found: {result['total_dips_detected']}")

Readiness: Placed
Probability: 62.0%
Dips found: 1.0

## OTHER MODELS

### Logistic

In [52]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [53]:
y_pred = log_model.predict(X_test_scaled)
acc_logis = accuracy_score(y_test, y_pred)
print(acc_logis)

0.782608695652174

### XGBOOST

In [54]:
from xgboost import XGBClassifier
xg_model = XGBClassifier(n_estimators=100,max_depth=4,learning_rate=0.1,random_state=42,eval_metric='logloss'
)



y_xg = df_features["placement_ready"].map({
    "Not Placed": 0,
    "Placed": 1
})

X = df_features[FEATURES]
y = y_xg

# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_xg,
    test_size=0.2,
    random_state=42,
    stratify=y_xg
)


xg_model.fit(X_train, y_train)
y_pred = xg_model.predict(X_test)

In [55]:
acc_XG = accuracy_score(y_test, y_pred)

acc_XG

0.7681159420289855

### SVM

In [56]:
from sklearn.svm import SVC


X = df_features[FEATURES]
# Binary target
y_svm = df_features["placement_ready"].map({
    "Not Placed": 0,
    "Placed": 1
})

X_train, X_test, y_train, y_test = train_test_split(
    X,y_svm,test_size=0.2,random_state=42,stratify=y_svm
)

In [57]:
svm_model = SVC(kernel='rbf',C=1.0,gamma='scale',random_state=42, probability=True)

svm_model.fit(X_train_scaled, y_train)

SVC(probability=True, random_state=42)

In [58]:
y_pred = svm_model.predict(X_test_scaled)


acc_svm = accuracy_score(y_test, y_pred)

acc_svm

0.6956521739130435

In [59]:
print(acc_svm, acc_logis, acc_RandomFor, acc_XG)

0.6956521739130435 0.782608695652174 0.7681159420289855 0.7681159420289855

In [60]:
print(df_features["placement_ready"].value_counts())

placement_ready
Placed        173
Not Placed    171
Name: count, dtype: int64

In [61]:
df_features['Student_ID'].duplicated().sum()

np.int64(0)

## PREDICTION SYSTEM

In [62]:
def placement_predct(student_df, feature_list, model, scaler=None):

    engineered_features = build_student_features(student_df)

    input_df = pd.DataFrame([engineered_features])[feature_list]

    if scaler is not None:
        input_df = scaler.transform(input_df)

    prediction = model.predict(input_df)[0]
    probability = model.predict_proba(input_df)[0][1]

    return {"readiness_score" : round(probability * 100, 2),
            "total_dips_detected": engineered_features['dip_count'],
            "current_sem_is_dip": bool(engineered_features['last_sem_dip'])}

In [63]:
new_student = pd.DataFrame({
    "Semester": [1, 2, 3,4,5,6,7],
    "SGPA": [7.45, 8.12, 6.50, 6.50, 6.45, 5.6, 4.68], 
    "Attendance": [82, 85, 80, 70,72,22,15],
    "Internals": [21, 2, 23, 21, 10, 23, 20]
})

In [64]:
student_df = new_student
model = log_model
feature_list = FEATURES 


scaled_models = [log_model, svm_model]

if model in scaled_models:
    x = scaler
else:
    x = None

In [65]:
result = placement_predct(student_df, feature_list, model, scaler= x)
print(f"Probability: {result['readiness_score']}%")
print(f"Dips found: {result['total_dips_detected']}")

Probability: 94.47%
Dips found: 3.0

### Model's Prediction

In [66]:
models = {
    "Random Forest": rf_model,
    "Logistic Regression": log_model,
    "SVM": svm_model
}


for name, model in models.items():

    # Decide scaling automatically
    if model != rf_model:
        x = scaler
    else:
        x = None

    result = placement_predct(
        student_df,
        FEATURES,
        model,
        scaler=x
    )

    print(f"\n{name}")
    print(f"Probability: {result['readiness_score']}%")
    print(f"Dips Found: {result['total_dips_detected']}")

Random Forest
Probability: 57.0%
Dips Found: 3.0

Logistic Regression
Probability: 94.47%
Dips Found: 3.0

SVM
Probability: 44.74%
Dips Found: 3.0

#### Random Forest Feature Importance

In [67]:
importance = pd.Series(
    rf_model.feature_importances_,
    index=FEATURES
).sort_values(ascending=False)

print(importance)

internals_avg        0.223005
current_sgpa         0.179413
sgpa_mean            0.168227
sgpa_trend           0.147328
consistency_score    0.129051
attendance_mean      0.097888
dip_count            0.043574
last_sem_dip         0.011513
dtype: float64

#### Logistic Regression Weightage

In [68]:
importance = pd.Series(
    log_model.coef_[0],
    index=FEATURES
).sort_values(ascending=False)

print(importance)

internals_avg        1.540331
current_sgpa         1.272334
last_sem_dip         0.096147
dip_count           -0.040609
attendance_mean     -0.102151
consistency_score   -0.135297
sgpa_trend          -0.158354
sgpa_mean           -1.232977
dtype: float64